# Generated by Django 5.2.7 on 2025-11-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='processing', max_length=50),
        ),
    ]
