# Generated by Django 5.2.7 on 2025-11-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='valid_star_range',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='stars',
            new_name='rating',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating_range'),
        ),
    ]
